resources:
- ../default

patches:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/grafana-operator/grafana-operator:v5.0.0
    newName: quay.io/grafana-operator/grafana-operator
    newTag: latest
