name: release
on:
  push:
    tags:
      - .*

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Publish Helm charts
        run: |
          cd helm
          yq -i '.image.repository = "gchr.io/${{ github.repository }}"' grafana-operator/values.yaml
          helm registry login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          helm package --app-version ${{ github.ref_name }} --version ${{ github.ref_name }} grafana-operator
          helm push grafana-operator-${{ github.ref_name }}.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts
  
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Prepare
        id: prep
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - uses: ko-build/setup-ko@v0.6
        with:
          version: v0.12.0

      - name: Build and push
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
        run: |
          ko build --sbom=none --bare --platform linux/arm64,linux/arm/v7,linux/amd64 -t ${{ github.ref_name }} \
            --image-label org.opencontainers.image.title=grafana-operator \
            --image-label org.opencontainers.image.description="An operator for Grafana that installs and manages Grafana instances & Dashboards & Datasources through Kubernetes/OpenShift CRs" \
            --image-label org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }} \
            --image-label org.opencontainers.image.revision=${{ github.sha }} \
            --image-label=org.opencontainers.image.version=${{ github.ref_name }} \
            --image-label=org.opencontainers.image.created=${{ steps.prep.outputs.BUILD_DATE }}
